// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCABKA-ytK47Q26oU9X9vop3BM0AJ5PFuM',
    appId: '1:470847058839:web:8dc9bd4f33ed2adb718ad2',
    messagingSenderId: '470847058839',
    projectId: 'groupiee-1324',
    authDomain: 'groupiee-1324.firebaseapp.com',
    storageBucket: 'groupiee-1324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP-NXAEm3x3aQVUHY1rHUkQMuOjds7rFA',
    appId: '1:470847058839:android:c18e5a5e847d58f0718ad2',
    messagingSenderId: '470847058839',
    projectId: 'groupiee-1324',
    storageBucket: 'groupiee-1324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCqBYU1wz7IFilyiqrWwze45YlWeHz36c',
    appId: '1:470847058839:ios:6e31662733a0163c718ad2',
    messagingSenderId: '470847058839',
    projectId: 'groupiee-1324',
    storageBucket: 'groupiee-1324.appspot.com',
    iosClientId: '470847058839-tc0ne3tfig6jskdagtcnhf7v2mrmmu5d.apps.googleusercontent.com',
    iosBundleId: 'com.praneeth.groupiee',
  );
}
